package control;

public enum Commads {
	C_SAVE_PRODUCT, C_SAVE_CLIENT, C_SAVE_INVOICE, C_ADD_PRODUCT, C_ADD_CLIENT, C_ADD_INVOICE,
	C_DELETE_PRODUCT, C_DELETE_CLIENT, C_DELETE_INVOICE, C_ADD_PRODUCT_INVOICE,
	C_DELETE_PRODUCT_ACTION, C_DELETE_CLIENT_ACTION, C_DELETE_INVOICE_ACTION
	
}
